gyroidos/cml

- daemon/control.c
- removed unneeded DEBUG
- added include
> fixed Android build

- common/file.c
- common/file.h
- control/control.c
- daemon/c_cgroups.c
- daemon/cmld.c
- daemon/cmld.h
- daemon/control.c
- daemon/control.proto
This patch add the control command "reload" to reread the
container config files from storage. Thus, newly created
container configs will be added as new containers. Already
created containers are skipped for now.
> cmld: added ability to reload container configs  + c_cgroups: check for already mounted tmpfs

- daemon/Makefile
- daemon/cmld.c
- daemon/guestos.c
- daemon/tpm2d.proto
- daemon/tss.c
- daemon/tss.h
- tpm2d/Makefile
- tpm2d/control.c
- tpm2d/ml.c
- tpm2d/ml.h
- tpm2d/tpm2_commands.c
- tpm2d/tpm2d.h
- tpm2d/tpm2d.proto
This patch provides the implementation to provide an IMA-style
measurement list (ML) for container images. The cmld (guestos.c)
measures (generates the hash) of each read-only image before starting
the container and sends it to the tpm2d through the tss.h interface.
The tpm2d maintains the measurement list and extends new measurements
from the cmld to the TPM's PCR11, thus not interfering with the
IMA default in PCR10.
The ML is send at the end of the attestation request in the tpm2_control
interface to a remote verifier.
A sample ml_entry looks like this:
ml_entry: "11 4bf6d86968043a73640ebeb82d6a67481bc66f2ae7a9f5589d57fdebf3011b20 \
ima-ng sha256:ace88b9a1573d8e0d2555d89b408b8a15d36f4d2ed1468d46143e4e0e9ff9579 \
/data/cml/operatingsystems/trustx-coreos-1/root.img"
> Implemented IMA-style measurement list (ML) for containers

- daemon/c_net.c
- daemon/container_config.c
If the user sets invalid mac address kernel will reject the
creation of the veth pair with "99: Address not available".
In that case, an assertion for the if_name of that interface
is triggered in c_net.c causing a fatal abort.
This patch gives only sanitized mac addresses out of the
config sub module, overwriting the user provided misconfiguration.
> daemon: avoid Assertion `if_name' failed by sanitizing mac

- daemon/container.c
- daemon/control.c
Without this check undefined behaviour may trigger a general
protection fault causing cmld to abort.
> cmld: container check running state before exec command in c_run

- common/file.c
- common/file.h
- daemon/c_vol.c
- daemon/c_vol.h
- daemon/container.c
- daemon/guestos.proto
- daemon/guestos_config.c
- daemon/mount.h
This could be used to share config files between containers.
e.g. create a guestos with an bind mount rw and another one with bind mount ro:
guestos to provide config
```
mounts {
image_file: "someconfig.cfg"
mount_point: "/etc/someconfig.rw"
fs_type: "none"
mount_type: BIND_FILE_RW
}
```
guestos to use config:
```
mounts {
image_file: "someconfig.cfg"
mount_point: "/etc/someconfig.ro"
fs_type: "none"
mount_type: BIND_FILE
}
```
> cmld: introduce mount type for bind mounting files

- daemon/device.proto
- tpm2d/attestation.proto
- tpm2d/tpm2d.proto
This commit fixes Github issue #80 opend by Heosuabi:
"
The following protobuf files don't have a java_package option:
./tpm2d/attestation.proto
./tpm2d/tpm2d.proto
./daemon/device.proto
Without the java_package option the default package is . after compiling.
This can be problematic depending on the application and the environment.
"
> Fixed: Missing java_package in some protobuf files

- common/Makefile
- control/Makefile
- converter/Makefile
- daemon/Makefile
- rattestation/Makefile
- run/Makefile
- scd/Makefile
- scd/control.c
- scd/ssl_util.c
- service/Makefile
- tpm2_control/Makefile
- tpm2d/Makefile
This patch targets the build system. It enables:
- stack canaries (-fstack-protector-all)
- stack safe-guard pages that protect against legacy stack-clashing attacks
(-fstack-clash-protection)
(https://www.qualys.com/2017/09/26/linux-pie-cve-2017-1000253/cve-2017-1000253.txt)
- full relro to protect against GOT overrides for control flow hijacking
(-Wl,-z,relro -Wl,z,now)
- position independent compilation and PIE linking. This allows ASLR to
take effect also on the text segment (useful for throttling ROP)
- compile-time warnings against wrongful casts and incorrect format string
usage
for all project binaries (control, converter, daemon, logcat,
rattestation, run, sc, service, tmp2_control, tmp2d)
> Enable compile- and link-time binary hardening

- common/nl.c
- common/nl.h
- common/proc.c
- daemon/Makefile
- daemon/c_cgroups.c
- daemon/c_cgroups.h
- daemon/cmld.c
- daemon/container.c
- daemon/container.h
- daemon/container.proto
- daemon/container_config.c
- daemon/container_config.h
- daemon/uevent.c
- daemon/uevent.h
This patch allows to configure usb devices to be allowed
or exclusively assigned to a container. It further introduces
a uevent subsystem to handle hotplug events for those devices.
Since unplugging and re-plugging an usb device, increments the
minor number of the corresponding character device.
>  cmld: Forward usb devices to container

- daemon/crypto.proto
Specify to use proto2 as syntax to fix compiler warning about missing
syntax. Currently proto2 is used as default value for syntax version,
when no syntax is defined.
Fixes #90
> Fix missing syntax version

- common/dir.c
- common/network.c
- common/proc.c
- common/proc.h
- converter/docker.c
- converter/util.c
- converter/util.h
- daemon/Makefile
- daemon/c_user.c
- daemon/c_user.h
- daemon/c_vol.c
- daemon/c_vol.h
- daemon/container.c
- daemon/container.h
- daemon/container.proto
- daemon/container_config.c
- daemon/container_config.h
**Main patch is: cmld: activate user namespace for containers** 
This patch activates the user namespace according to the container
configuration file (default = on). A new container submodule c_user
is introduced which handles the uid and gid mappings in the root
namespace. Each container is mapped to a new range of 10000 uids
starting from uid 30000.
The c_user module also provides an interface which is used by c_vol
to shift uids and gids of directories. This feature depends on the
non-mainline shifts.
The rest are fixes and cleanups, see commit messages
> Feature: Make userns available for trustx

- common/network.c
- common/network.h
- common/protobuf.c
- daemon/c_net.c
- daemon/c_run.c
- daemon/c_vol.c
- daemon/cmld.c
- daemon/cmld.h
- daemon/container.c
Main patches: 
1. **cmld: Move all physical network interfaces to c0 if private netns.** 
This patch allows to unshare the network name space of c0, while
maintaining the behaviour of accessing all physical network interfaces.
Thus, c0 can act as unprivileged router for containers even without
having access to the root network namespace. This is also necessary
to run c0 inside a user namespace. Since, if user namespace is enabled,
the container has no privileges in the shared root network namespace.
2. **daemon/c_net: Move all veth endpoints to netns of c0**
This patch also moves the veth endpoints of configured interfaces to
the netns of c0. However, also the configuration of those endpoints
have to be done in the target namespace. We do this by forking a
helper process of cmld and join …
> Feature: private netns for c0

- daemon/c_cgroups.c
- daemon/c_user.c
This patch shifts cgroups child directories for containers
to their corresponding mapped root uid. This allows systemd
to manage cgroups in its cgroup namespace if userns is enabled.
> cmld: Shift ids of cgroups in case of userns is enabled

- daemon/device.proto
Patches the default c0os to "trustx-coeros". This patch is related to 
patches in trustme_build and meta-trustx. Together they aim to allow a user to not build any c0 but rather supply it manually without the system entering a bootloop.
> device.proto: update the default c0 OS to 'trustx-coreos'

- daemon/cmld.c
- daemon/container.c
- daemon/control.c
- daemon/guestos_mgr.c
- daemon/uevent.c
bugfix 1:
Basename may modifiy the input string. Thus, we have to duplicate
the path string before use of basename.
bugfix 2:
fixes issue #100:
> daemon/uevent.c: fixed device node creation and runtime net if handling

- daemon/c_vol.c
If CONFIG_SECURITY_SELINUX_DISABLE is set, /sys/fs/selinux exist but SELinux contexts can't be set.
> Fixed is_selinux_enabled()

- daemon/guestos_mgr.c
`end_offset` underflows if `cacertlen == 0` resulting in a segmentation
fault in the following `strncmp(cacert + end_offset, ...)`.
> Fix memory corruption bug in guestos_mgr_register_newca()

- daemon/smartcard.c
`end_offset` underflows if `cert_len == 1` resulting in a segmentation
fault in the following `strncmp(cert + end_offset, ...)`.
> Fix memory corruption bug in smartcard_push_cert()

- common/network.c
- common/network.h
- common/nl.c
- daemon/c_net.c
- daemon/cmld.c
- daemon/cmld.h
- daemon/container.c
- daemon/uevent.c
Avoid name clashes with container-internal interface renaming mechanisms by prefixing the interfaces on cmld startup
> Rename network interfaces on cmld startup

- daemon/c_vol.c
- daemon/c_vol.h
- daemon/smartcard.h
- scd/token.c
- scd/token.h
This PR bind mounts the token communication sockets created by the scd to the corresponding container.
To achieve this, the mount propagation type of the container's /dev tmpfs is changed to MS_SHARED to propagate the socket mount events to the container's mount namespace.
> Bind token comm socket to corresponding container

- common/event.c
- daemon/c_cgroups.c
- daemon/c_net.c
- daemon/c_run.c
- daemon/c_user.c
- daemon/c_vol.c
- daemon/cmld.c
- daemon/cmld.h
- daemon/device.proto
- daemon/device_config.c
- daemon/device_config.h
- daemon/main.c
- daemon/mount.c
- daemon/mount.h
This patch-set allows to run cmld in a standard distribution such as debian for development purpose.
The standard distribution runs in the CML. Neither a c0os nor a c0 container is necessary
to run user containers. The network/routing part which is usually done by c0/in c0's network
namespace is kept in CML.
Further since standard distributions do not support shiftfs, a preliminary support for kernel's
without shiftfs is provided by this patch set.
> Feature: Hostedmode for cmld to allow cmld to run inside standard linux distributions

- daemon/c_vol.c
- daemon/uevent.c
- scd/scd.c
New interfaces can't be moved to c0 in hosted mode,
this PR adds the necessary checks to reflect this
> Adapt interface addtion in hosted mode

- control/control.c
This two patches modifies the password handling of the control tool:
- first patch fixes control flow of all container specific commands and therefore
also for change_pin (see Issue #148) and ask for passwords only if container exists.
- second patch ask the user for the password on container start if no key param is given
- third patch fixes the run command paramter order, because of uuid check as first parameter is now for all container specific commands
> control: Password handling and control flow

- daemon/guestos_mgr.c
New CA certs to be registered are hashed by the SCD to check whether they have already been registered. This has been done using a temporary file located under /tmp. As the cmld unshares his mount namespace an remounts /tmp this file has not been accessible to the SCD for hashing anymore.
This PR is a temporary fix that uses /data/cml/shared as fs location that is accessible to both the cmld and scd.
In the future it might be considered to move the SCd into a container and establish a more general way to share data between the cmld and a specific container.
> daemon/guestos_mgr.c: fix ca_register

- common/ns.h
- daemon/cmld.c
- daemon/container.c
- daemon/container_config.c
- daemon/control.c
- daemon/smartcard.c
- tpm2d/tpm2d.c
In common/ns.h: adapted namespace_exec(...) arguments to match ns.c definition.
In daemon/control.c: added nullptr checks, fixed typos / bugs.
In daemon/container_config.c: added missing cast.
In tpm2d/tpm2d.c: fixed typo / bug.
In daemon/smartcard.c: added nullptr checks.
In daemon/cmld.c: added nullptr checks.
In daemon/container.c: added nullptr checks.
Notes:
- In daemon/control.c:`control_handle_message(...)`: 
- (Future) Potentially reconsider the extent of error messages for each command, e.g. when looking at case CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_EXEC_INPUT, where the error message noted a missing container (this error was never triggered though) vs all other container commands which simply return. 
- Case CONTROLLER_TO_DAEMON__COMMAND__CONTAINER_EXEC_INPUT: Is a check for …
> Sanity checks added, fixed typos and small bugs

- common/str.c
- common/str.h
- daemon/c_vol.c
- scd/scd.c
- scd/token.c
- scd/usbtoken.c
Fixes for issues to the APDU relay:
- Add .sock extention to relay sockets
- Keep relay connection open
- Log hexdumps of APDU communication
> Fixes for the APDU-Relay

- common/Makefile
- common/ns.c
- common/ns.h
- common/proc.c
- common/proc.h
- daemon/Makefile
- daemon/c_cap.c
- daemon/c_cap.h
- daemon/c_run.c
- daemon/c_service.c
- daemon/c_service.proto
- daemon/container.c
- daemon/container.h
- service/Makefile
- service/exec_cap_systime.c
This PR provides ability to set system time from a privileged container.
privileged means per definition in guestos, the container itself runs
in unprivileged user namespace.
Main commit is:
**daemon/c_cap: Introduce function to exec with cap_sys_time:**
To provide the ability to set system time in a privileged container
with userns enabled, we introduce the c_cap_exec_capsystime() function.
It could be used to execute a binary inside the target container
with cap_sys_time in root userns. To keep isolation impact as low as
possible, we switch to the user witch is mapped to the root user in
the userns of the container. Further, we drop all other capabilities,
except CAP_SYS_TIME.
> Exec process with cap_sys_time in container with enabled userns

- common/str.c
- common/str.h
- daemon/cmld.c
- daemon/cmld.h
- daemon/container.c
- daemon/container.h
- daemon/smartcard.c
- daemon/uevent.c
- scd/control.c
- scd/token.c
Currently, the cmld and scd do not reflect token detachments and attachments during runtime in their internal data structures.
This pull request handles these events based on the kernel uevents triggered by USB device attachments / detachments.
Also, this PR deletes the container's encryption key as long as it is no longer needed by the cmld.
Thereby, it is assured that the container's sensitive data can no longer be accessed once a token was detached
> Handle token attachment and detachment + related fixes

- README.md
Added README.md which states the requirement for the DCO on
commits inside a pull request.
> README.md: Added DCO documentation

- common/network.c
- common/network.h
- common/proc.c
- common/proc.h
- daemon/Makefile
- daemon/c_net.c
- daemon/cmld.c
- daemon/cmld.h
- daemon/container.c
- daemon/container_config.c
- daemon/time.c
- daemon/time.h
- daemon/uevent.c
- daemon/uevent.h
Main feature is: **daemon/container, c_net: allow to use mac string for netif assignment**
The container config file allows to set a repeated string for network
interface names which are assigned/moved to the container net namespace.
This field now accepts a string representation of mac addresses in form
of "00:11:22:33:44:55", too. The protobuf inteface is not touched and the
descission if the string is a mac or ifname is made in c_net submodule.
However, see commit messages for details.
> Assign netif by mac and fixed netdev assignment (mainly in uevent)

- daemon/cmld.c
- daemon/uevent.c
- daemon/uevent.h
Instead of just trigger coldboot events by exec of udevadm trigger, walk
through sysfs and trigger synthetic events only for allowed devices.
Internally the uuid of the container is used to trigger synthetic events
to allow injecting the resulting events to the corresponding container
only.
> uevent: properly handle coldboot for containers 

- control/control.c
- daemon/cmld.c
- daemon/cmld.h
- daemon/control.c
- daemon/control.proto
Only allow a subset of commands to the CMLD as soon as the device is provisioned. Add a command to set the device provisioned. As the command to get the container config is not allowed anymore, additionally introduce a new command that only gets the pin-entry field of the container config in order to determine how the pin is entered by the user (feature-usb-pin-reader).
> Feature cmd limitation

- daemon/c_cgroups.c
Removed some critical devices from default white list of allowed
devices. Especially input devices are forbidden now, since that
would have allowed to implement keyloggers for physically connected
keyboard devices attached to CML or c0.
> daemon/c_cgroups: more restrictive white list for devices

- daemon/cmld.c
- daemon/cmld.h
- daemon/container.c
- daemon/container.h
- daemon/container_config.c
- daemon/container_config.h
- daemon/control.c
- daemon/control.proto
- daemon/device.proto
- daemon/device_config.c
- daemon/device_config.h
The API in 'container.c' for container_new() is expanded to also
take buffers for signature and certificate for a container config.
These are given to container_config_new() in 'contrainer_config.c'.
The external API in 'container.c' allows to leave these buffers empty,
and the container_config_new() will deal with reading and storing
corresponding date from/to disk.
The signature verification is also made in container_config_new().
Signature failure result in an empty container object and thus makes
the implementation almost transparent to cmld.c and control.c.
The new feature can be enabled in device.conf 'signed_configs: true'.
Currently, default is set to false to maintain previous behaviour.
Getting signature and certificate through control interface is not
yet implemented and needs …
> daemon: Introduce container config signature validation

- daemon/cmld.c
- daemon/smartcard.c
This commit ensures that a container that is configured to be used
with a usbtoken is not being created if its associated ustoken could
not be initialized.
> daemon/smartcard.c: Fix container being created even if its usbtoken could not be

- daemon/container.c
GuestOS version of containers usually would be updated to latest
available GuestOS verison. However, if container configs are signed,
we want to have the GuestOS version fixed as defined in that config.
Thus, we only do the implicit update if we are allowed to also update
the container config.
> daemon/container: keep GuestOS version of signed container configs

- common/protobuf.c
Free the buffer after message has been send in
protobuf_send_message
> Common: Fixed memory leak.

- daemon/audit.c
- daemon/audit.h
- daemon/c_audit.c
- daemon/c_audit.h
- daemon/cmld.c
- daemon/container.c
main commit: daemon/audit: Introduce kernel audit handling
Extended the audit module to register cmld as auditd in the kernel
audit framework. Initially a simple logging to cmld's log file of
kernel audit log records is provided.
> Audit: kernel audit handling

- common/cryptfs.c
Extension to the creation of the crypt device in cryptfs_setup_volume_new(). Instead of creating a crypt device, we will now firstly create an integrity device using the same kernel interface as for crypt. The original crypt device will than be mounted on top of the integrity device.
Signed-off-by: Florian Jakobsmeier <florian.jakobsmeier@aisec.fraunhofer.de>
> common/cryptfs: provide dm-integrity device support

- daemon/c_cgroups.c
- daemon/c_net.c
- daemon/c_net.h
- daemon/cmld.c
- daemon/container.c
- daemon/container.h
- daemon/container.proto
- daemon/container_config.c
- daemon/container_config.h
Provide an option in container config which allows to set a cpu core
assignment for containers. This option is used 1:1 for configuring
the cgroup cpuset subsystem to exclusively assign the provided cpus
in form of "n-m" to the corresponding container.
+ some deprecated code cleanup and bugfixes
> daemon/container, c_cgroups: Add simple cpu core assignment

- common/audit.c
- common/audit.h
- common/nl.c
- daemon/audit.c
- daemon/audit.h
- service/service.c
This PR moves the CML specific portions of the audit code in libcommon to the CML.
Especially, the enums defining the CML specific audit event types are moved to the daemon code.
Instead, the audit record generation code now expects the audit event type as char pointer.
Also, a missing netlink ACK during registration as auditd via netlink on some platforms is worked around by this commit.
> Audit refactoring + fixes

- tpm2d/tpm2d_shared.h
The define for the path containing the device certificat was missing
the tpm2d base path as prefix. This is fixed now.
> tpm2d/tpm2d_shared: fixed path for device.cert

- daemon/c_vol.c
Since mkfs.btrfs returns an error if the lately integrated dm-integrity
device is used, this quick fix just deactivates the integrity device for
btrfs volumes for now.
> daemon/c_vol: Quick fix btrfs format failed on integrity device

- common/cryptfs.c
- common/cryptfs.h
- daemon/c_vol.c
- daemon/smartcard.c
- tpm2d/nvmcrypt.c
1. This is the real fix for integrity device setup and also inverts the
Quick-Fix (commit b7238cd5e889fca73eb2144e55472c7117754aa3).
2. We now use a separate meta device for integrity data
3. Further, we switched authenticated encryption scheme to HMAC XTS
> common/cryptfs: Propper dm_crypt device setup on integrity device

- daemon/audit.c
- daemon/c_audit.c
- daemon/c_audit.h
- daemon/c_service.c
- daemon/container.c
- daemon/container.h
- service/service.c
mem_free of protobuf structures lead to a memory corruption in the
daemon/audit submodule. We fixed this by resturcteing and using the
corresponding protobuf_free methods to free the protobuf structures.
Further, some frees of buffers allocated by getline and other
memory related cleanups are provided in this commit.
> daemon/audit,c_audit: restructured and fixed protobuf memory handling

- daemon/container.c
- daemon/container.h
- daemon/smartcard.c
This commit changes the token removal process in smartcard.c
s.t. the token's flag file is removed on container removal only.
> smartcard: unlink token flag file on container removal only

- daemon/audit.c
- daemon/audit.h
- daemon/cmld.c
- daemon/smartcard.c
- scd/control.c
- scd/scd.c
- scd/usbtoken.c
This PR adds minor fixes.
It moved the USB token deinitialization code that handles token detachments after the container stop to ensure correct token initialization if the token is re-attached.
Also, a audit message reflecting the cmld start time is added and the return values during USB token user authentication is fixed such that the scd responds with the correct message code.
> Fixes for token detachment handling + boot time audit message

- daemon/Makefile
- daemon/cmld.c
- daemon/smartcard.c
- scd/scd_shared.h
The SCD is now started during cmld and smartcard init.
> daemon/smartcard: Start SCD during smartcard init

- daemon/tss.c
On hardware platforms that take longer times to initialize all components
the current timeout causes the cml startup to fail.
Therefore, this commit removes the timeout
to give the platform the time it needs to initialize the TPM2.
> daemon/cmld: Remove timout aborting TPM2D connect

- daemon/cmld.c
Recently introduced move of scd start to cmld's smartcard subsystem
caused that CMLD_SOCKET_DIR is not created if tpm2d or scd is started by
init before cmld start. Thus, the creation of the cmld control cli
socket caused a FATAL abort. We now create that directory before the
cmld cli control socket is created.
> daemon/cmld: create missing cml's socket dir for control socket

- daemon/Makefile_lsb
- daemon/cmld.c
- daemon/cmld.h
- daemon/main.c
- daemon/smartcard.c
- daemon/tss.c
- daemon/tss.h
Since tpm2d and scd are now started by cmld, those processes needs to be stopped by cmld on exit, too.
This series fixes this and also some other quirks corresponding a clean exit.
> Startup and proper cleanup of tpm2d and scd

- daemon/audit.c
To avoid flooding the logs, change the log level of certain
messages
> cmld: changed log level for audit message

- Jenkinsfile
- daemon/c_net.c
- scripts/ci/VM-container-tests.sh
Currently, the veth cleanup code for c0 joins the net namespace only.
As the cleanup code determines existense of an interface based on /sys/class/net
it is necessary to also join the mount namespace of c0
s.t. the sysfs reflects the interfaces present in the net namespace.
Also, the cleanup routine is currently called twice,
this commit removes the additional loop.
> c_net: Fix veth cleanup in c0

- Jenkinsfile
- scripts/ci/VM-container-tests.sh
Reduce amount of RAM allocated for the VM
to avoid resource conflicts during builds.
Also, this commit limits the amount of concurrently executed VMs
during functional tests to 1 in order to assure correct cleanup.
> VM-container-test.sh: Reduce RAM allocated for VM and introduce lock

- daemon/control.c
Reduced the commands that are allowed to be send over the
control interface when executing the CC Mode.
Signed-off-by: Florian Jakobsmeier <florian.jakobsmeier@aisec.fraunhofer.de>
> daemon/control: Reduced Control Command Interface in CC Mode

- rattestation/hash.c
- rattestation/ima_verify.c
Use the generic EVP digest functions instead of the
SHA-256 digest functions
> rattestation: Switched to OpenSSL EVP interface.

- common/uuid.c
Removed prepended common/ as the files are in the same folder.
Otherwise, standalone builds linking against the common
library fail
> common/uuid: Fixed include paths

- scd/sc-hsm-lib/sc-hsm-cardservice.c
This PR fixes the include path of ctapi.h and removes an unused variable
> sc-hsm-cardservice: Fix include path and unused variable

- Jenkinsfile
- common/cryptfs.c
- Jenkinsfile: We checkout the corresponding branch in the trustme_main repo.
- bugfix: common/cryptfs: replaced fsync by O_DRIECT during integrity format
> Jenkinsfile: use branch from jenkins instead of zeus + bugfix

- Jenkinsfile
This fixes a typo which caused an empty manifest_branch variable.
> Jenkinsfile: Fixed typo in variable manifest_branch

- scripts/ci/unit-testing.sh
Lately, the run tool was removed from the cml repo. We forgot to
remove the dependency here. This is fixed now.
> scripts/ci/unit-testing.sh: removed dependency to run tool

- daemon/c_cgroups.h
- daemon/c_net.c
- daemon/c_net.h
- daemon/c_vol.c
- daemon/container.h
- daemon/container_config.c
- daemon/guestos_mgr.c
- daemon/guestos_mgr.h
- daemon/smartcard.c
- scd/control.c
Systemd expects /dev/console to be there, thus just link the
first tty to the contaienr if there is one configured in the
container config. A further patch needs to create a pty as
replacement if no tty is mapped.
> daemon/c_vol: map first tty to /dev/console in container

- daemon/uevent.c
During container start cold boot uevents are triggered for containers
only by setting the UUID as synth_uuid in the event. This is masked
from the event before forwarding. However we accidentally forwarded
the original event instead of the newly created one without the
synth_uuid. This is herby fixed!
> daemon/uevent: Fixed masking of synth_uuid of coldboot events

- rattestation/attestation.c
- rattestation/ima_verify.c
- rattestation/modsig.c
Convert the configuration pcr values to byte arrays
before comparing them with the byte arrays of the
measurements
> rattestation: compare byte arrays instead of strings

- daemon/hw_x86.c
The character device for the hardware RNG '/dev/hw_random' does not
exist anymore. Switch to correct path '/dev/hwrng'.
> daemon/hw_x86: fixed path for hardware RNG

- common/logf.c
- daemon/cmld.c
- daemon/main.c
- daemon/time.c
- scd/scd.c
- tpm2d/tpm2d.c
**common/logf:** Release resources occupied by lof_handler
On logf_unregister() the memory resources used during registering
where not free'd. Thus, we now release this memory to avoid mem leaks
on release of logfile handlers. This was implicitly assumed by all
implementations of log rotate mechanisms in the CML.
**daemon/time,cmld:** audit system clock changes
If system clock changes is detected by time submodule, we now generate
an audit event. Further, also register the clock check already on start
of c0 and not only after each subsequent container start.
We also fixed up some excessive logging to trace.
> Bugfixes: logf_handler mem_leak, time submodule audit event

- scripts/format-code.sh
As discussed, my adjusted code fomatting script that allows selecting the files to be formatted. 
If used without options, the script behaves exactly as before, i.e. formats all files. With the newly introduced options, the output can be silenced and only any combination of new (untracked), modified (unstaged) and/or staged files can be formatted. Usual usage: ./scripts/format-code.sh -u (only formats modified (unstaged) files, much faster than default command). 
> scripts: Added options for code formatting

- daemon/c_net.c
On stopping udhcpd check if pid_file exists before allocating
resources which may trigger an assertion in mem module on
allocating buffer for the corresponding pid_file.
Signed-off-by: Michael Weiß <weiss@m4st3rnet.de>
> daemon/c_net: Fix cleanup of network interfaces (udhcpd)

- daemon/Makefile_lsb
- daemon/cmld.c
- daemon/init.d/cmld
- daemon/scd.c
- daemon/scd.h
- daemon/tss.c
- daemon/tss.h
- scd/init.d/cml-scd
- tpm2d/Makefile_lsb
- tpm2d/init.d/tpm2d
This commit contains minor fixes for the cmld, scd and tpm2d init scripts.
> daemon/scd/tpm2d: Fixes for init scripts

- daemon/control.c
Added checks to prevent the start, stop and change_pin command to be send to cml daemon.
Signed-off-by: Florian Jakobsmeier <florian.jakobsmeier@aisec.fraunhofer.de>
> daemon/control.c: Prevent Start/Stop/Change_Pin for C0

- Jenkinsfile
This commit increases the spare space on the data partition
in order to execute the tests correctly.
(cherry picked from commit 2e1e9eee532cd250232b6e80255bb59eb85623ac)
> Jenkinsfile: Configure extra space in datapart

- rung/rung.c
Handle force option if oci delete is triggered. Otherwise the
container id would not be set correctly in the protobuf message
which is sent to the cmld.
> rung/rung: handle force option of delete command

- common/file.c
- common/file.h
- daemon/c_fifo.c
- daemon/c_run.c
- daemon/c_vol.c
This PR fixes the cleanup of the c_fifo module and enables use of FIFOs in hosted mode
> Fixes: c_fifo cleanup + hosted mode, overlay/tmpfs permissions, c_run

- common/file.c
- common/file.h
- daemon/c_fifo.c
- daemon/c_fifo.h
- daemon/c_run.c
- daemon/c_vol.c
- daemon/container.c
This commit ports fixes for the c_fifo and c_run subsystems as well as a patch for the permissions of overlay/tmpfs mount points
> Backports: c_fifo cleanup, overlay/tmpfs permissions, c_run

- daemon/Makefile
- daemon/c_cgroups.c
- daemon/c_idmapped.c
- daemon/c_shiftid.c
- daemon/c_uevent.c
- daemon/c_user.c
- daemon/c_vol.c
- daemon/container.c
- daemon/container.h
Use mainline idmapped mounts instead of shiftfs
This depends on idmapped squahsfs mounts which was also was submitted to mainline Linux 
(https://lore.kernel.org/all/20221024191552.55951-1-michael.weiss@aisec.fraunhofer.de/)
and will hopefully make it in 6.2. Meanwhile the old mechanism was refactored to a c_shiftid module
which remains default unless Make option IDMAPPED is set to 'y'
> Idmapped cidmapped

- daemon/c_cgroups.c
- daemon/c_vol.c
Currently, some containers fail to boot because the directory persmissions of /dev don't allow creation of the /dev/pts directory. Therefore, this PR creates /dev/pts when /dev is mounted.
Also, a misleading error message is printed when applying the allowed/assigned device lists for non-present devices.
> daemon/{c_vol, c_cgroups}: Fixes for /dev/pts and device assignment

- daemon/c_cgroups.c
- daemon/c_vol.c
This PR backports fixes for /dev/pts and a misleading error message when assigning non-present devices
> Backports: Fixes for daemon/c_vol and daemon/c_cgroups

- daemon/guestos_config.h
Adapt typedef for GuestOSConfig to fit protoc-c generated source files from newer versions.
GuestOSConfig is a typedef already provided by protoc-c generated header files.
This was successfully tested on
- Debian Buster: protoc-c --version
protobuf-c 1.3.1
libprotoc 3.6.1
- Debian Bullseye: protoc-c --version
protobuf-c 1.3.3
libprotoc 3.12.4
- Debian sid: protoc-c --version
protobuf-c 1.4.1
libprotoc 3.12.4
> Fix compatibility with newer protoc-c versions

- Jenkinsfile
- common/logf.c
- common/protobuf.c
- control/Makefile
- control/cc_mode
- daemon/container.c
- daemon/guestos_config.h
- daemon/guestos_mgr.c
- daemon/guestos_mgr.h
- scripts/ci/VM-container-commands.sh
- scripts/ci/VM-container-tests.sh
This commit backports the following fixes from the dunfell branch
- Always use GuestOS version from container config when using signed config
- Adapt typedef to support recent protoc versions
- Enable CI tests for ccmode images
> Backports for OS version handling, recent protoc-c versions and the CI Pipeline

- common/logf.proto
- control/control.c
- daemon/control.c
- daemon/control.proto
This new command copies all log files from /data/logs to /tmp/00000000-0000-0000-0000-000000000000/var/logs to make them accessible in c0.
Signed-off-by: Corinna Lingstädt <corinna.lingstaedt@aisec.fraunhofer.de>
> daemon/control: add 'control retrieve_logs' command

- .gitignore
This commit ignores files related to the build process such as pb-c.{h,c}, object files and binaries.
> .gitignore: Ignore build files

- .gitignore
- common/ssl_util.c
- common/ssl_util.h
- common/ssl_util.test.c
Introduce functions for encryption and decryption with AES in ECB and CTR mode.
> common/ssl_util: Introduce AES functionality

- rattestation/attestation.c
The printed variables are of type size_t. size_t is a typedef for `long unsigned int` on 64bit architectures and `unsigned int` on 32bit architectures. This PR fixes the format string to correctly recognize the size of type size_t on all architectures and not always assume 64bit. This is required to fix compilation for the arm32 (e.g. colibri-imx6ull board) architecture.
Signed-off-by: Johannes Wiesboeck <johannes.wiesboeck@aisec.fraunhofer.de>
> Correct portable format string for size_t

- daemon/audit.c
We switched from mktemp() to mkstemp() for generating the temporary file name in audit_log_record(). This avoids the corresponding gcc warning.
> daemon/audit: avoid 'warning: the use of `mktemp' is dangerous'

- Jenkinsfile
- daemon/c_fifo.c
This PR adapts the behavior of c_fifo s.t. fifos are only closed and reopened on read errors
Also, a fix for skipping the sstate mirror sync in PR builds is included.
> Fixes for c_fifo

- .gitignore
- daemon/Makefile
- daemon/c_automnt.c
- daemon/c_automnt.h
- daemon/container.c
This commit backports the auto-mounting functionality for block devices
that are accessible to the container through a container config entry.
> daemon/automount: Backport block dev auto-mounting

- scripts/ci/Dockerfile
Yocto kirkstone requires lz4 and zstd as additional HOSTTOOLS. Install them into the Docker Container.
Signed-off-by: Johannes Wiesboeck <johannes.wiesboeck@aisec.fraunhofer.de>
> scripts/ci/Dockerfile: Install missing HOSTTOOLS

- Jenkinsfile
As cmld_git.bbappend is not used and not created by init_ws.sh, cat'ing the file breaks the build. Further, as meta-appends is not used for cmld anymore, there is no use for it anymore. Remove.
> Jenkinsfile: Remove setting cmld_git.bbappend

- daemon/control.c
Reload containers should not be available in CC mode. Containers are reloaded automatically on updates.
> daemon/control: remove RELOAD_CONTAINERS in CC mode

- common/Makefile
This commit changes the Makefile of libcommon
such that th ar tool specified by the build environment is used.
This is needed in Yocto builds, for example, as Yocto specifies the toolchain
to be used for a particular build.
> common/Makfile: Call ar via variable

- daemon/c_uevent.c
fixed logic error in getting device from event devtype by checking if devtype
is 'disk' or 'partition' then set 'b', otherwise set 'c'.
> daemon/c_uevent: Fixed expression in uevent handler callback

- Jenkinsfile
This commit adapts the Jenkinsfile to access the variables CHANGE_TARGET and BRANCH_NAME via env. to avoid exceptios if thesese variables are not set by Jenkins.
> Jenkinsfile: CHANGE_TARGET and BRANCH_NAME via env

- daemon/c_vol.c
This will provide an update path from previous installations with GuestOSes which do not have a dm-verity hash image and root hash in its configuration file. Thus, it is possible to update the CML to its new version and the GuestOS could be updated later on independently.
Previous behavior: If we update the CML and do not switch to the new CML version in runtime, the older cmld will fail to import the new GuestOS configuration due to missing protobuf definitions. However, if we update the CML and do a reboot to get the new version running the c0 with its old GuestOS config wont start anymore.
The later is now possible with this patch. Thus, the old c0 gets up and running to provide the interface for the GuestOS update with new configuration options containing verity information.
> daemon/c_vol: Allow to start without dm-verity support

- scripts/ci/VM-container-tests.sh
Switch Qemu's cacheing mechansim of disk image files to directsync.
This should avoid some disk state errors when killing the Qemu VM.
> scripts/ci/VM-container-tests: use directsync on disk image files

- scripts/ci/VM-container-tests.sh
Switch Qemu's cacheing mechansim of disk image files to directsync. This should avoid some disk state errors when killing the Qemu VM.
(cherry picked from commit 862e3c9262ce5d001bfc143b5d6c60a91d0dd94c)
> Backport: scripts/ci/VM-container-tests: use directsync on disk image files

- daemon/hotplug.c
- scd/Makefile
- scd/token.c
This PR adds fixes for handling of USB tokens by the CML:
- scd/token.c: Properly unlink event accepting incoming connections  from the scd's internal list
- daemon/hotplug.c: Wait for device node to become available before sending TOKEN_ADD request
- Properly handle linker flags in scd/Makefile
> Fixes related to token handling

- common/file.c
- common/file.h
- common/proc.c
- common/proc.h
- control/control.c
- daemon/cc_mode/control.proto
- daemon/cmld.c
- daemon/cmld.h
- daemon/control.c
- daemon/control.proto
- service/service.c
Main commit of this feature: 
daemon/control: Provide device stats through control interface
Introduce a new protobuf message command DEVICE_STATS to retrieve
statistics about memory and disk utilization of the CML.
This could be used in c0 to monitor if container space may run out or
system disk is getting full due to any reasons.
> Provide device stats through control interface

- common/protobuf.c
- common/protobuf.h
- control/control.c
- daemon/control.c
- daemon/control.proto
- daemon/lxcfs.c
- scripts/ci/VM-container-commands.sh
- scripts/ci/VM-container-tests.sh
This PR adapts the implementation of GET_LAST_LOG to support large log files.
To this end, large log files are sent by fragments.
> Fix logfile retrieval for large logfiles

- daemon/c_cgroups.c
- daemon/c_cgroups_dev.c
- daemon/c_vol.c
- daemon/cmld.c
- daemon/compartment.c
- daemon/compartment.h
- daemon/container.c
- daemon/container.h
- daemon/container_config.c
- daemon/container_config.h
- daemon/control.c
- daemon/oci.c
Now the compartment type is hold as flag as well as the namespace configuration. The previous compartment_type_t is now specified as container_type_t to transparency map the existing container API. The compartment flags attribute is currently hidden in compartment_t and only exported to the higher level container module.
> daemon: Introduce compartment flags for feature configuration

- daemon/c_seccomp.c
This PR removes the erroneously placed SYS_creat syscall number from an error message.
> daemon/c_seccomp: Fix error message

- daemon/c_seccomp.c
Currently the seccomp code is only developed and tested for x86 and provably breaks the arm builds. Until the code is properly ported to arm we enable the module only for x86.
> daemon/c_seccomp.c: Use only for x86

- daemon/c_cgroups_v2.c
- daemon/c_idmapped.c
- daemon/c_uevent.c
**cgroups_v2**:
The inotify listener for the cgroup events file where never removed. Thus, causing a mem_leak and exhaustion of inotify fds on start stop cycle. We now properly cleanup the groups->inotify_cgroup_event in c_cgroups_cleanup().
**idmapped**:
To get the upper directory mapped correctly we need to add a mnt
struct as mapping for the corresponding image. Otherwise the upper
directory would just be created somewhere in the cml storage. This
was resulting in exhausting the ram since "persistent" data of the
containers where written to /tmp/ of the CML which is a tmpfs.
> bugfixes: c_cgroups_v2 inotify handling, c_idmapped overlay handling

- common/dir.c
- common/event.c
- daemon/c_idmapped.c
This commit initializes the global variable event_inotify_io so that the inotify descriptor is reused after being initialized the first time. If this variable is not correctly initialized, event_inotify_fd() will always create a new inotify descriptor (without properly closing prior ones) which leads to running into the process' inotify limit after a few container starts.
> Bugfix: Fix running out ouf inotify descriptors

- daemon/c_smartcard.c
- daemon/hotplug.c
In hotplug_usbdev_sysfs_foreach_cb(), do not exit early without proper cleanup of memory buffers. Instead set the bool veariable 'found' correctly and use this to propererly return 0 or 1. Thus, dir_foreach() also can count the succeeded callbacks correctly.
> daemon/hotplug: fixed sysfs handling for device search

- daemon/c_uevent.c
In c_uevent_create_device_node(), the decision if a block or a character device should be created depending on the uevent devtype is now made correctly.
> daemon/c_uevent: Fixed logic for block and char dev decision

- scripts/ci/VM-container-commands.sh
- scripts/ci/VM-container-tests.sh
This PR improves output when the container startup fails. Also, it introduces an environment variable "CML_DEBUG" to allow enabling the script's debugging output for the caller.
> VM-container-tests.sh: Increase output on error

- Jenkinsfile
- common/cryptfs.c
- common/list.c
- common/protobuf.c
- common/protobuf.h
- daemon/audit.c
- scripts/ci/Dockerfile
This PR adds a number of fixes to increase debuggability and readability of debugging logs:
- Make necessary adaption to enable compilation with sanitizers
- Set log level to TRACE for a number of log messages
- Add more detailed tracing to common/protobuf.c
> Fixes related to sanitizers and debugging logs

- daemon/c_vol.c
- service/Makefile
- service/Makefile_lsb
This fixes a Lintian error by explicitly marking the binary as static.
Needs https://github.com/gyroidos/meta-trustx/pull/206 for CI.
> Renamed static build of 'cml-service-container' to 'cml-service-container-static'

- converter/util.c
- rattestation/attestation.c
- rattestation/container_verify.c
- rattestation/hash.c
This PR replaces all hash implementations in the converter
module that use the deprecated SHA{1,256} (openssl/sha.h) functions
by equivalent functions from the EVP API.
> Replace OpenSSL 3.0 deprecated digests

- common/audit.c
Do not include protobuf-c-text headers if not required.
> common/audit: dependency fix

- daemon/Makefile
- daemon/bpf_insn.h
- daemon/c_cgroups_sockopt.c
This is a sample module which can be used to inline eBPF programs which are loaded and attached to the containers cgroup at container start. It maintains a list of progs to detach and cleanup at previously attached progs at container cleanup.
> daemon/c_cgroup_sockopt: Module to inline some sockopt eBPF progs

- daemon/c_cgroups_sockopt.c
Fixe typo: IF_NULL_RETUN(prog) -> IF_NULL_RETURN(prog)
> daemon/c_cgroups_sockopt: Fixed typo in c_cgroups_sockopt_prog_free()

- common/protobuf.h
Previous limit was 1MB, change this to the google
protobuf default message size limit of 64 MB.
> common/protobuf: Changed message limit to 64 MB

- daemon/cmld.c
This PR moves the callback unregistering to the correct location s.t. the config_sync_cb is only unregistered if a sync is actually to be performed. Also, an erroneous debugging print is fixed.
> daemon/cmld.c Fixes for config_sync_cb

- common/cryptfs.c
Commit fe960e1c00f6 ("common/dm: Add macro for devfs location") changed the DM_PATH_PREFIX by stripping the trailing "/". This breaks the device path in cryptfs.c. To fix this we need to add the "/" in the format string of the helper cryptfs_get_device_path_new().
This should also fix tpm2d-based encrypted boot of GyroidOS.
Fixes: fe960e1c00f6 ("common/dm: Add macro for devfs location")
> common/cryptfs: add missing "/" in cryptfs_get_device_path_new()

- common/verity.c
- daemon/Makefile
- daemon/c_automount.c
- daemon/c_uevent.c
- daemon/c_vol.c
- daemon/cmld.c
- daemon/compartment.c
- daemon/compartment.h
Removed automount feature from c_uevent. Added it to c_automount.
This allows for disable automount at build, since it seems to brick start/stop cycles on some systems.
Use new module flag to cleanup c_vol late after any other module for now. This should also fix
start/stop cycles if c_automount is enabled.
> Refactor automount to own submodule, cleanup c_vol late

- daemon/guestos_mgr.c
Commit 3c8fd49d582f "daemon/guestos_mgr: Check available disk space" introduced disk space check during update procedure of guestoses. The check was made on guest_os_dir(os). However this dir does not yet exists at this early stage of the update procedure.
Check against 'guestos_basepath' instead.
This fixes the followng error:
[448] <ERROR> guestos_mgr.c+452: Function file_disk_space_free failed
Fixes: 3c8fd49d582f ("daemon/guestos_mgr: Check available disk space")
> daemon/guestos_mgr: Use guestos_basepath for disk space check

- daemon/c_cgroups.c
- daemon/c_cgroups_sockopt.c
Inclusion of hardware.h was missed during testing because the modules are deactivated in the default build configuration.
> daemon/{c_cgroups,c_cgroups_sockopt}: Remove hardware.h include

- common/proc.c
- common/proc.h
- daemon/c_cap.c
- daemon/c_seccomp.c
- daemon/c_vol.c
- daemon/cc_mode/container.proto
- daemon/cmld.c
- daemon/compartment.c
- daemon/compartment.h
- daemon/container.c
- daemon/container.h
- daemon/container.proto
- daemon/container_config.c
- daemon/container_config.h
- daemon/mount.h
main commits which holds the feature are:
[daemon/compartment: Introduce new flag COMPARTMENT_FLAG_MODULE_LOAD](https://github.com/gyroidos/cml/commit/bc3b8c6f8a6c5e5917fc3b201bffe87c79de53b7)
The new flag COMPARTMENT_FLAG_MODULE_LOAD will be used in followup
commits to emulated module loading for those containers which have
this flag set.
Only allow this flag to make it to the internal compartment struct if
module signatures are enforced in the running kernel. We use the new
helper compartment_is_module_sig_enforced(void) to check the
proc file "sys/module/module/parameters/sig_enforce" which says "Y"
in that case.
If compartment flag is set we now emulate the finit_module() syscall.
The emulation does properly check that the corresponding process
holds the CAP_SYS_MODULE in its …
> Module loding for containers

- daemon/c_seccomp.c
During finit_module() syscall emulation do not pass the parameters as is anymore. Until we do not have a proper module parameters sanity checking, we white out parameters since there may be dangerous ones.
> daemon/c_seccomp: white out module parameters during emulation

- common/proc.c
- common/proc.h
- daemon/c_cgroups_dev.c
- daemon/c_seccomp.c
Main commit:
[daemon/c_seccomp: handle mknod() and mknodat()](https://github.com/gyroidos/cml/pull/454/commits/a4e419ba938ac922bd4ce8d80d5c42fbe94382d3)
We only do user space emulation for block and char devices, otherwise
the bpf-based secompfilter directly jumps to SECCOMP_RET_ALLOW and let
the kernel process the syscall.
We emulate mknod() by mknodat() for code dedup. mknod() and mknodat()
have the same arguments, except that mknodat has dirfd as first argument:
int mknod(const char *pathname, mode_t mode, dev_t dev);
int mknodat(int dirfd, const char *pathname, mode_t mode, dev_t dev);
We therefore use an offset +1 for the data.args array to retrieve syscall
parameters from seccomp req in case of mknodat() and set dirfd to AT_FDCWD
in case of mknod().
Further, we check CAP_MKNOD of …
> mknod emulation

- daemon/c_seccomp.c
clang does some funny stuff with the comment inside of the macro block of our seccomp filter struct. Thus, refactored to make formatter happy.
> daemon/c_seccomp: fixed formatting of seccomp filter macro

- daemon/hotplug.c
The current procedure to activate all devices in the CML init script and then added all available network interfaces to the cmld's internal tracking list, is racy.
E.g., the modprobe for a driver will be made by 'init' which will create the corresponding net device. However there is some time needed until the corresponding sysfs structures are populated. The cmld gets startet and initializes its internal list of net devices on basis if '/sys/class/net/<ifname>' is present. This is not always ready at then. The result is that the corresponding net interface will not be added to the internal tracking list and stays in the init root netns forever.
Thus, to avoid missing some interface get moved to c0 on stratup, let hotplug_init() trigger all relevant events again. That way the hotplug …
> daemon/hotplug: trigger all net devices (add) uevents on early boot

- scd/scd.c
Accidentialy hw_serial was set by HARDWARE_NAME instead of HARDWARE_SERIAL and hw_name was set to "generic" in any case. This is fixed now.
Fixes: 8adb459f10b3 ("scd/scd: Fixed common_name in device.csr generation")
> scd/scd: Fixed hw_serial in common name of device.csr

- Jenkinsfile
- common/file.c
- common/file.h
- daemon/cmld.c
- daemon/guestos_mgr.c
- daemon/mount.c
This commit adds a disk space check to the container config update routine in order to prevent the loading of new configs which would allocate more disk space for a container than available.
> daemon/cmld: Check available disk space on container config update

- common/logf.c
This PR disables stream buffering for CML log files.
> common/logf: Disable buffering

- scd/usbtoken.c
The current approach for monitoring token presence interferes with secure
messaging channels. Therefore, this commit introduces the APDU "MANAGE
CHANNEL" in is_card_present() which does not impact secure messaging.
> scd/usbtoken: fix faulty APDU for is_card_present

- daemon/c_cgroups_dev.c
- daemon/c_hotplug.c
USB Tokens should remain in the CML. Thus, to prevent communication interruption introduced in case of misconfiguration where usb devices are allowed in containers, just ignore configured access to TOKEN devices.
Using the new explicit deny list approach of the c_cgroups_dev
module, access to USB devices which are used as TOKENs by other
containers are now denied during hotplug events. We maintain a
global list of such tokens, which are is maintained during
compartment_new() and compartment_free().
After a plug event occurs it is check if the USB device is in the
global list of tokens. Remember the serial since the minor number of
a USB device is incremented during plug/unplug. If it is, it is
further checked if the container object also is allowed to access the
corresponding low level …
> daemon/c_hotplug: Do not allow usb devices of type TOKEN in container

- common/ssl_util.c
This commit fixes length of the returned UUID buffer to container 36 bytes for UUID + null terminator.
Fixes: 2744ee01ad55 ("common/ssl_util: added helper to get uuid from a certificate/csr")
> common/ssl_util: Fix null terminator in ssl_get_uid_from_cert_new()

- common/file.c
- daemon/download.c
This PR increaes the block size used for OS download operations. Also, a heap allocated buffer is now used to perform the copy operation.
> Increase OS download blocksize

- common/ssl_util.c
- scd/scd.c
This PR fix the following asan log:
================================================================= ==229==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 46 byte(s) in 1 object(s) allocated from:
#0 0x7fa24ee4ea2a in __interceptor_malloc [..]/gcc-11.4.0/libsanitizer/asan/asan_malloc_linux.cpp:145
#1 0x7fa24ec1f236 in __vasprintf_internal [..]/glibc/2.35-r0/git/libio/vasprintf.c:71
#2 0x7ffcc3f74897  ([stack]+0x20897)
Direct leak of 40 byte(s) in 1 object(s) allocated from:
#0 0x7fa24ee4ea2a in __interceptor_malloc [..]/gcc-11.4.0/libsanitizer/asan/asan_malloc_linux.cpp:145
#1 0x7fa24e8afc78 in CRYPTO_malloc [..]/openssl-3.0.15/crypto/mem.c:196
Indirect leak of 575 byte(s) in 17 object(s) allocated from:
#0 0x7fa24ee4ea2a in __interceptor_malloc …
> common/ssl_util: asan fixes

- daemon/Makefile
- daemon/c_seccomp/seccomp.c
- daemon/c_seccomp/seccomp.h
- daemon/c_seccomp/sysinfo.c
[daemon/c_seccomp: introduce sysinfo() emulation](https://github.com/gyroidos/cml/pull/487/commits/0183f0a6b86b860befc3dec0bf7f99e59f93db2a)
Currently lxcfs is used to virtualize several procfs files to
use cgroup values instead of system wide values for resources.
However, not all user space tools rely on procfs but make use of
the sysinfo() syscall, which again provides system wide values
for resource utilization. Only uptime is already be correctly
handled by the time namespace.
Thus, we have to emulate the sysinfo() call to, e.g., provide
ram limits also for applications which use sysinfo.
Values are used either directly derived from cgroups files or in
case of loads[], we use the proc provided values, which are
emulated by lxcfs if available.
sysinfo() is an unprivileged syscall …
> daemon/c_seccomp: added emulation for sysinfo() syscall

- daemon/cc_mode/control.proto
- daemon/control.proto
CC mode
GET_LAST_LOG is experimental in CC mode. Therefore add definitions for LogMessage, device_uuid and corresponding enums to CC mode proto file.
> daemon/cc_mode/control: Incorporate definitions for log retrieval in

- daemon/c_seccomp/sysinfo.c
During development of sysinfo emulation the TRACING output was activated. This was accidentally committed to the mainline feature in commit dd7e20d0bc54 "daemon/c_seccomp: introduce sysinfo() emulation". Just deactivate this now.
Fixes: dd7e20d0bc54 ("daemon/c_seccomp: introduce sysinfo() emulation")
> daemon/c_seccomp/sysinfo: deactivate TRACING logs

- common/file.c
- common/ns.c
- daemon/audit.c
- daemon/c_seccomp/seccomp.c
- daemon/c_seccomp/sysinfo.c
- daemon/control.c
In function audit_record_from_textfile_new() the return value of fread() was checked against non-zero as error indicator. This was wrong. We now check if the return value has the expected amount of bytes to be read.
Fixes: 526d6ccf99d3 ("daemon/audit: locking of audit log file")
> daemon/audit: properly check return value of fread() + seccomp log verbosity

- daemon/c_seccomp/seccomp.c
syscall emulation code currently makes trouble for some container payloads. Thus, just disbale it for now by jumping to instruction "BPF_STMT(BPF_RET | BPF_K, SECCOMP_RET_ALLOW)" in the syscal filter.
> daemon/seccomp: disble emulation of sysinfo()

- common/event.c
- common/macro.h
- common/network.c
- common/nl.c
- common/protobuf.c
- common/verity.c
- daemon/audit.c
- daemon/c_service.c
- daemon/c_smartcard.c
- daemon/c_vol.c
- daemon/crypto.c
This commit adapts the logging verbosity of the cmld and libcommon logs. To this end, the log level of a number of messages ischanged from DEBUG to TRACE and overrides of the loglevel in common/network.c and common/verity.c are removed. Also, log messages of checks in common/macro.h are rephrased.
> daemon/common: Log verbosity reduction

- daemon/Makefile
- daemon/c_xorg_compat.c
- daemon/cc_mode/container.proto
- daemon/cmld.c
- daemon/compartment.h
- daemon/container.c
- daemon/container.h
- daemon/container.proto
- daemon/container_config.c
- daemon/container_config.h
Recent Linux kernel 6.9 changed device link of parent devices
in the sysfs. Newer xorg servers can handle this. However, to be
compatible with container payload which includes no recent xorg
server, we introduce this module. It will mount a tmpfs on the
/sys/class/graphics directory and links the included files, so
that it will compatible with old matching logic.
Especially, the link in /sys/class/graphics/fb0 may not include
a pci suffix to get recognized as platform device by legacy xorg
servers. Thus we link to bus/platform instead.
> Xorg compat

- common/macro.h
- daemon/Makefile
- daemon/c_seccomp/adjtimex.c
- daemon/c_seccomp/init_module.c
- daemon/c_seccomp/ioctl.c
- daemon/c_seccomp/mknod.c
- daemon/c_seccomp/mount.c
- daemon/c_seccomp/seccomp.c
- daemon/c_seccomp/seccomp.h
- daemon/c_seccomp/sysinfo.c
[daemon/c_seccomp: introduce mount() emulation](https://github.com/gyroidos/cml/commit/abdb2c24684d6ebe46e29d4e917a9998da39d31f)
Currently only handle tmpfs, ramfs and overlay mounts in cmld.
These mounts are allowed in unprivileged user namespace anyway.
However, since we also handle mknod() to allow to create device nodes
on such file systems. Without interception, the kernel implicitly
sets SB_I_NODEV to those mounts, leaving us with unusable device
nodes as open would fail with -EACCESS. Thus, handling this in the
cmld on behalf of the container, we get a mounted fileystem without
SB_I_NODEV. This will allow systemd's feature 'private devices' to
work in a cmld container.
> Seccomp mount

- common/network.c
- daemon/cmld.c
At first lines of network_list_link_ns does not match with lines returned in an element of the returned list list_line. Usually a line of list_line contained all line from one interface. However, sometimes this got garbled. We now read the output of the sub process with getline() and create a new list_line element each time we get an new line with ifindex at the beginning and if not we just append the string of the existing last element.
> common/network: more robust parsing in network_list_link_ns

- daemon/Makefile
This commit adapts daemon/Makefile s.t. the corresponding define is actually passed to the compiler if CC_MODE_EXPERIMENTAL is set to 'y'.
> daemon/Makefile: Fix for CC_MODE_EXPERIMENTAL

- daemon/c_hotplug.c
- daemon/cmld.c
[daemon/cmld: reattach token on container reload](https://github.com/gyroidos/cml/commit/46d0db234cad938c52b8bf12acda9c98a6f736d4)
On reload the new container object is created with container_new()
and afterwards the previous object is deleted by a call to
container_free(). Makes sens to first try to create the new updated
container object and only if this succeeds, the old object is
destroyed. However on container_new() the token is attached to the
scd and on container_free() it is removed:
Thus we now have the following behavior:
1) We have the token attached in the scd. The config updated kicks
in and we get a new container object created by container_new().
A second attach is made in the scd:
<INFO>  control.c+221: Token already exists.
2) That is ok, we just ignore that in the scd …
> Token fixes: reattach token on container reload

- common/ssl_util.test.c
After merge of gyroidos/cml#495, this commit removes two #ifdef statements that maintained compatibility with OpenSSL versions prior to 3.0.
> common/ssl_util.test: Remove OpenSSL <3.0 compat

- scd/Makefile
- scd/sc-hsm-lib/cardservice.c
- scd/sc-hsm-lib/cardservice.h
- scd/scd.c
- scd/token.c
- scd/usbtoken.c
- scd/usbtoken.h
Allow more fine grained control about what is going to be built into the scd binary according to sc-hsm-lib cardservice.
> scd: refactoring sc-hsm-cardservice build

- scd/scd.c
Removing the deprectated Android code in commit f75193ffc0b56 ("scd: refactoring sc-hsm-cardservice build") left over unused argc and argv parameters. Just declare those as UNUSED.
Fixes: f75193ffc0b5 ("scd: refactoring sc-hsm-cardservice build")
> scd/scd: fix unused parameters in main

- daemon/c_automount.c
- daemon/cmld.c
While destroying a container, a use-after-free occurred, since the used observer callback in cmld.c frees the container and therefore also the compartment before all other registered observers where called.
Similarly to the container reload, we now use the observer finish callback to do a delayed free after all compartments observer callbacks have been run.
This fixes asan error:
================================================================= ==203==ERROR: AddressSanitizer: heap-use-after-free on address \
0x511000000838 at pc 0x557253082656 bp 0x7ffe4cfee190 sp 0x7ffe4cfee180
READ of size 8 at 0x511000000838 thread T0
#0 0x557253082655 in compartment_notify_observers daemon/compartment.c:1681
#1 0x557253088149 in compartment_sigchld_handle_helpers daemon/compartment.c:705
#2 …
> daemon/cmld: fix use-after-free during compartment destroy

- common/ssl_util.c
- common/testdata/cert_confs/openssl-ssig-cml.cnf
- common/testdata/cert_confs/openssl-ssig-rootca.cnf
- common/testdata/cert_confs/openssl-ssig-subca-cml.cnf
- common/testdata/cert_confs/openssl-ssig-subca.cnf
- common/testdata/cert_confs/openssl-ssig.cnf
- common/testdata/create_certs.sh
- common/testdata/gen_testvectors.sh
- daemon/c_automount.c
- daemon/c_service.c
- daemon/cmld.c
- daemon/guestos_mgr.c
- scd/Makefile
- scd/scd.c
Current rework of gyroidos reositries replaced all legacy variable nameing thus we have to take this into account here, too. We replace the build variable TRUSTME_SCHSM by SCHSM.
> cleanup rework of trustme leftovers

- common/ns.c
- common/ns.h
- common/pidfd.h
- daemon/c_net.c
- daemon/c_seccomp/seccomp.c
- daemon/c_seccomp/seccomp.h
- scd/sc-hsm-lib/cardservice.h
* Address network interfaces with correct name, which we get from an id
* Join namespace by ID when removing network interface
* Remove wrong semicolon
> Fix cleanup of network interfaces

- common/Makefile
This PR adapts the target dependencies for compilation of audit.proto in common/Makefile to ensure the 'protobuf' target actually provides audit.pb-c.{h,c}.
This fixes races during build:
make -C common protobuf
| make[1]: Entering directory /dir/service-static-1.0+999/common' | protoc-c --c_out=. audit.proto
| In file included from audit.c:28:
| audit.h:32:10: fatal error: audit.pb-c.h: No such file or directory
|    32 | #include "audit.pb-c.h"
|       |          ^~~~~~~~~~~~~~
> common/Makefile: Fix dependencies for audit.proto

- common/file.c
In file_copy, the input file size got calculated  using the min of fstat(2) and the provided count*bs. For non-regular files like /dev/zero this lead to wrong behaviour as fstat reports 0 for such files. Now, for positive counts always count*bs is taken as input file size. In case a write operation returns 0 it is assumed that no input data is left for copying.
> common/file: Fix handling of non-regular files in file_copy

- common/cryptfs.c
- common/fd.c
- common/fd.h
- common/file.c
- common/logf.c
- common/macro.h
- daemon/main.c
- scd/scd.c
This PR leverages a buffer allocated via calloc's copy-on-write-based approach together with the fd_write implementation in common/fd.c implementation to increase the speed of initial formatting while not requiring a large amount of physical memory.
> common/cryptfs: Adapt integrity dev formatting

- common/logf.c
- common/logf.h
- control/control.c
- daemon/control.c
- daemon/control.proto
Log files are removed upon successful retrieval. Except the currently used log files. This behavior is controllable by the caller of GET_LAST_LOG.
> daemon: Remove logs upon retrieval

- daemon/c_user.c
- daemon/cmld.c
- daemon/cmld.h
Refactor UID_MAX such that it is only defined in one location. Set value to 65536 to assure that also 65535 is mapped as id.
see https://github.com/systemd/systemd/blob/main/docs/UIDS-GIDS.md#considerations-for-container-managers
> daemon/c_user,cmld: Increase and refactor UID_MAX

- common/event.c
This commit adapts the event loop implementation to always check whether timers expired regardless of whether epoll_wait returned pending io events.
> common/event: Always check timers after epoll

- common/sock.c
Modify socket file permissions after binding to R,W,X by owner only (0700)
> common/sock: Modify socket Permissions

- daemon/c_service.c
Fix the log message created by the cmld upon a container request for the DNS server to be used
> daemon/c_servce: Fix log message

- common/hex.c
- common/macro.h
- common/munit.c
- control/control.c
- converter/converter.c
- daemon/bpf_insn.h
- daemon/c_cap.c
- daemon/c_net.c
- rung/rung.c
- tpm2_control/tpm2d_control.c
- tpm2d/tpm2d.c
The clang version shippped with Debian Trixie comes with several formatting changes compared to the version shipped by Debian Bookworm. Therefore, the swich to Debian Trixie as base image for CI builds in gyroidos/gyroidos#79 makes integration of these formatting changes necessary.
> treewide: Adapt to updated clang formatting
