gyroidos/cml

control/control.c, daemon/control.c, daemon/control.proto
enable running commands in the container specified by its uuid
=> extended functionality of the control tool:

common/mem.c, common/mem.h, control/control.c, daemon/c_cap.c, daemon/c_cap.h, daemon/c_cgroups.c, daemon/c_cgroups.h, daemon/c_run.c, daemon/c_run.h, daemon/container.c, daemon/container.h, daemon/control.c, daemon/control.proto
Ported + extended /run to new subsystem c_run used to execute processes in the given container's context
=> c_run subsystem

common/event.c, common/event.h, common/list.c, common/list.h, common/mem.c, control/control.c, daemon/c_run.c, daemon/c_run.h, daemon/container.c, daemon/control.c
=> Patch c_run subsystem

service/service.c
We now check if we are running as pid 1 (init). If not we do not
accept program parameters for child process and die.
This also fixes Github issue:
"Sending SIGINT to running cservice with arguments triggers shutdown #86"
=> service/service.c: only run signal handlers if running with pid 1

common/logf.c, common/network.c, common/nl.c, common/sock.c, control/control.c, daemon/cmld.c, daemon/container.c, daemon/control.c, scd/control.c, scd/ssl_util.c
This patchset is a collection of small, but critical bug fixes. Multiple memory and file descriptor leaks, NULL ptr dereferences and others have been patched.
Please refer to the description of the individual commit messages for more information.
=> General fixes

daemon/c_net.c, daemon/c_user.c, daemon/guestos_mgr.c, daemon/scd.proto, daemon/smartcard.c, daemon/smartcard.h, scd/control.c
=> Bugfix for push_guestos_config

common/Makefile, common/common.test.c, common/macro.h, common/macro.test.c, control/control.c, daemon/c_run.c, daemon/c_vol.c, daemon/container_config.c, daemon/guestos_config.c, daemon/smartcard.c, rattestation/attestation.c, rattestation/main.c, scd/ssl_util.c, tpm2d/nvmcrypt.c, tpm2d/rcontrol.c, tpm2d/tpm2_commands.c
Ahoi! As usual, information is in the commit message.
=> Fix and harden heap buffer allocation sites

common/mem.h
As discussed in #127. 
If you merge this patch, you can also safely close #127.
=> Remove NULL ptr assertion in mem_free

common/Makefile, control/Makefile, converter/Makefile, daemon/Makefile, rattestation/Makefile, run/Makefile, scd/Makefile, service/Makefile, tpm2_control/Makefile, tpm2d/Makefile
@fwruck As discussed some time ago.
Please check the commit's message before reviewing.
=> Separate development from production build

common/network.c, common/network.h, common/nl.c, common/nl.h, daemon/c_net.c, daemon/uevent.c
new pull request since jenkins did not recognize #137
=> correctly move wifi interfaces using generic netlink nl80211 

common/Makefile, control/Makefile, converter/Makefile, daemon/Makefile, daemon/c_fifo.c, daemon/uevent.c, scd/Makefile, service/Makefile, tpm2_control/Makefile, tpm2d/Makefile
Add debugging symbols to development builds + bugfixes
=> Minor makefile adaptions + bugfixes

common/fd.c, common/sock.c, common/sock.h, control/control.c, daemon/uevent.c, scd/Makefile, scd/control.c, scd/scd.c, scd/scd.h, scd/token.c, scd/token.h, scd/tokencontrol.proto, scd/usbtoken.c, scd/usbtoken.h
This PR aims to enable the scd to create a socket through which applications inside a container can send APDUs to their associated usbtoken.
The socket is created under /run/socket/tokencontrol/<UUID> as soon as a usbtoken is initiated in the scd.
ToDo:
=> [WIP] Feature/usbtoken apdu relay

Makefile, Makefile_lsb, control/Makefile_lsb, daemon/Makefile_lsb, daemon/c_vol.c, daemon/cmld.c, daemon/cmld.h, daemon/guestos_mgr.c, daemon/init.d/cmld, daemon/main.c, rattestation/main.c, scd/Makefile, scd/Makefile_lsb, scd/init.d/cml-scd, scd/scd.c, scd/scd.h, service/Makefile_lsb, tpm2d/tpm2d.c, tpm2d/tpm2d_shared.h
This patch-set allow log files, config files and persistent data files to be stored in LSB conform directories
instead of using '/data'
=> Lsb conform builds + bugfixes

daemon/c_cgroups.c, daemon/c_user.c, daemon/c_vol.c, daemon/container.c, daemon/container.h, daemon/container.proto, daemon/guestos_config.c, service/service.c
See commit messages for description.
Also some fixes are included to support ram limit application again.
Other fixes:
- populating dev
- setup mode
- user namspace uid offset handling
- service binary segfault
=> Properly activate and handle ram_limit of containers + fixes

daemon/c_user.c, daemon/uevent.c
=> Fixes uevent handling

common/network.c, common/protobuf.c, daemon/c_user.c, daemon/guestos.c, daemon/mount.c, daemon/smartcard.c, daemon/smartcard.h, daemon/uevent.c, scripts/ci/Dockerfile
See title of commit messages for more information.
=> Minor leak fixes and additional checks

daemon/c_user.c, daemon/cmld.c, daemon/container.c, daemon/smartcard.c, daemon/smartcard.h
Enhanced cleanup on container destruction
=> Enhanced cleanup on container destruction

common/proc.c, daemon/Makefile, daemon/c_vol.c, daemon/cmld.c, daemon/lxcfs.c, daemon/lxcfs.h, daemon/main.c
=> Feature: Lxcfs + Fix Setup mode

daemon/control.c
The check if a device is allowed in provisioned, non-provisioned, hosted,
privileged or non-privileged mode is unified in one function
=> daemon/control.c: Refactored handling of privileged and unprivileged messages

daemon/container.c
Since the key in container struct for the encrypted volumes is erased
after initial use, container reboots did not work anymore.
Now the c_vol and c_user submodules keep their state during reboots.
We do not invoke the corresponding cleanup and start hooks in that
case.
=> daemon/container: keep states for encrypted volumes during reboot

tpm2d/tpm2d.c
In case of disk encryption, tpm2d needs to be started early were the
data partition which is used to store key blobs is not yet available.
Hence, we need to start tpm2d twice in this scenario.
The first time to initialize disk encryption and the second time when
encrypted data partition is available. Then keys could be stored on
the encrypted partition.
This patch allows to start tpm2d with cmdline parameter -n (--nokeys)
to provide initial mode for using to unlock the disk encryption key.
=> tpm2d: allow to start tpm2d without initializing keys for attestation

scd/token.c, scd/usbtoken.c
Use TRACE macro for APDU relay debugging output
=> scd/usbtoken: apdu relay info as TRACE

daemon/c_cgroups.c, daemon/lxcfs.c, daemon/mount.c, daemon/mount.h
This fixes:
" cgroups.c: 55: cgroup_init: Failed to initialize cgroup driver
Failed to initialize cgroup support"
=> Lxcfs fixes 

tpm2d/swtpm-docker/Dockerfile
Added pip3 and python-setuptools to Dockerfile for the
tpm2d build
=> tpm2d: Added dependencies to Dockerfile

daemon/cmld.c, daemon/control.c
Signed-off-by: Joana Pecholt <joana.pecholt@aisec.fraunhofer.de>
=> daemon/audit: Null pointer fixes

scripts/ci/VM-container-tests.sh
This is a script with which the current cmld gets build, started in QEMU and tested. Help messages offer more information how to run it. Tests are executed over ssh using port-forwarding and all executed commands are checked for successful execution in whichever way possible (correct response status, lack of aborts, verification in subsequent command). Only if all tests passed does the script reach the end (message).
Please verify that the VNC connection is set up properly.
=> New container test script

Jenkinsfile, scripts/ci/VM-container-tests.sh
=> CI: Enable VM test script in Jenkinsfile

common/protobuf.c
=> common/protobuf: Removed fsync

rattestation/attestation.c, rattestation/hash.c, rattestation/hash.h, rattestation/ima_verify.c, tpm2d/rcontrol.c, tpm2d/tpm2_commands.c, tpm2d/tpm2d.h
Implement verification of the aggregated quote pcr value and attestation type advanced for tpm2d and rattestation
=> Rattestation

daemon/audit.c
Handle audit events emitted from our dm-integrity audit patch.
The target container is identified by the corresponding sysfs file
and the dm label which contains the uuid.
=> daemon/audit.c: dm-integrity audit log handling

tpm2d/nvmcrypt.h, tpm2d/tpm2d.proto
Signed-off-by: Christian Epple <christian.epple@aisec.fraunhofer.de>
=> tpm2d: Add interface description

.gitignore, daemon/cmld.c, daemon/cmld.h, daemon/container.c, daemon/container.h, daemon/container_config.c, daemon/container_config.h, daemon/control.c, daemon/smartcard.c, daemon/smartcard.h, scd/token.c
Just a draft, as the changes were not tested with a physical USB token yet
=> Tokenchange

daemon/c_vol.c, daemon/lxcfs.c, daemon/mount.c
This PR adds fixes for cmld execution in hosted mode
=> Fixes related to hosted mode

Jenkinsfile, scripts/ci/Dockerfile, scripts/ci/VM-container-commands.sh, scripts/ci/VM-container-tests.sh
This PR adds fixes and improvements to the Jenkins pipeline:
- Parallel image builds and tests
- Tests for image with USB token support
- Refactoring of VM-container-tests.sh
=> Parallel Jenkinsfile

scripts/ci/VM-container-commands.sh, scripts/ci/VM-container-tests.sh
This commit adds tests for container removals to
VM-container-tests.sh and VM-container-commands.sh.
=> scripts/ci: Container removal tests

common/uevent.c, common/uevent.h, daemon/c_net.c, daemon/c_uevent.c, daemon/container.c, daemon/container.h, daemon/hotplug.c, daemon/lxcfs.c
Fixed uevent forwarding and hotplug of netdevs
=> Bugfix uevent/hotplug subsystem

common/Makefile, common/cryptfs.c, common/cryptfs.h, common/dm.c, common/dm.h, common/fd.c, common/fd.h, common/loopdev.c, common/loopdev.h, common/verityfs.c, common/verityfs.h, daemon/Makefile, daemon/c_vol.c, tpm2d/Makefile
Refactored common functionality from cryptfs into
new module 'dm' to be used by a future module for
dm-verity. Refactored loopdev functions.
=> common: Refactoring

Jenkinsfile
This PR increases the spare space on the data partition
in order to execute the tests correctly.
=> Jenkinsfile: Configure extra space in datapart

common/protobuf.c
=> common/protobuf: Avoid error message on close

common/proc.c, common/proc.h, daemon/Makefile, daemon/bpf_insn.h, daemon/c_cgroups.c, daemon/c_cgroups_dev.c, daemon/c_cgroups_systemd.c, daemon/c_cgroups_v2.c, daemon/c_hotplug.c, daemon/c_idmapped.c, daemon/c_user.c, daemon/lxcfs.c
In this draft pull request I work on cgroupv2 support for the cmld!
=> Cgroup v2 support

daemon/cmld.c, daemon/guestos_mgr.c
=> Audit fixes

daemon/c_cgroups_v2.c
In the 'start_pre_exec' hook we apply another indirection (subcgroup for container child). This is at least needed to run systemd as container payload. We have to consider this intermediate cgroup in the 'add_pid' function, too. This, is called, e.g., by the c_run submodule to join the container's cgroup.
=> daemon/c_cgroups_v2: respect intermediate child cgroup in add_pid

daemon/hotplug.c
hotplug_rename_interface() the renamed devpath object was made on the original event instead of the one with the renamed ifname. Further, it was ignored anyway since the uev_chname was returned and not the uev_chdevname. We fixed that and additionally provide proper cleanup of memory and error handling.
=> daemon/hotplug: fixed renaming of devpath in hotplug_rename_interface()

daemon/cmld.c, daemon/control.c, daemon/uevent.c, daemon/uevent.h
Reload containers should not be available in CC mode. Containers are reloaded automatically on updates.
+ uevent fixes
=> V0.9 bugfixes

Jenkinsfile, scripts/ci/Dockerfile
Changes include:
- Install missing HOSTTOOLS to docker image
- Change Jenkinsfile to trigger the generic pipeline (this PR already includes the enhanced Jenkinsfile version without hardcoded repo names)
=> Kirkstone changes after dunfell rebase

daemon/c_shiftid.c
The code to mount overlayfs inside of userns was buggy and also not properly working for all of our use cases. Thus, we just removed that and now use the properly working code which was introduced for backward compatibility for kernels which did not support overlayfs mounts in userns anyway.
=> daemon/c_shiftid: removed overlayfs mounting in userns

Jenkinsfile, control/control.c, daemon/cc_mode/control.proto, daemon/control.c, daemon/control.proto, scripts/ci/VM-container-commands.sh, scripts/ci/VM-container-tests.sh
depends on https://github.com/gyroidos/meta-trustx/pull/195
=> Feature: Get_provisioned command and test cases

Jenkinsfile, common/file.c, common/reboot.c, daemon/container.c, daemon/control.c, daemon/main.c, service/service.c
This commit backports fixes from kirkstone to v0.9
=> Backport fixes

daemon/c_smartcard.c, daemon/cmld.c, daemon/compartment.c, daemon/compartment.h, daemon/container.c, daemon/container.h
PR to fix start/stop audit logging, as well as enabling correct state monitoring before starting/stopping containers
=> Start/stop Audit Log Ticket

daemon/c_seccomp.c
To allow ntpd to adjust system time by ntp_adjtime() we need to also emulate the adjtimex() syscall.
=> daemon/c_seccomp: emulate adjtimex() for ntpd compatibility

common/ssl_util.c
PKCS12_newpass seems to be broken in OpenSSL 3. Workaround uses PKCS_create in order to change softtoken passphrase.
=> Workaround PKCS12_newpass

daemon/c_vol.c, daemon/cmld.c, daemon/mount.c, daemon/mount.h, scripts/ci/VM-container-tests.sh
Added support to calculate necessary disk space before container creation. Creation will be abortet if not enough space is left.
=> daemon/cmld.c: Check disk space

.gitignore, service/Makefile
Add 'cml-service-container-static' to ignored files and make clean.
=> .gitignore: ignore 'cml-service-container-static'

common/cryptfs.c, common/fd.c, common/network.c, daemon/c_vol.c, daemon/cc_mode/container.proto, daemon/cmld.c, daemon/cmld.h, daemon/compartment.c, daemon/container_config.c, daemon/control.c, daemon/device.proto, scripts/ci/VM-container-commands.sh, scripts/ci/VM-container-tests.sh
This PR extends the integration tests and contains fixes for bugs discovered through the updated integration test suite.
Requires gyroidos/gyroidos_build#111 and gyroidos/meta-trustx#211
=> Test extensions + bugfixes

common/network.c, daemon/c_net.c
requires: https://github.com/gyroidos/meta-trustx/pull/212
=> ssh access to cml layer

common/dm.c, common/event.c, daemon/c_cgroups_v2.c, daemon/c_smartcard.c, daemon/c_uevent.c, daemon/c_user.c, daemon/cmld.c, daemon/compartment.c, daemon/guestos_mgr.c, daemon/guestos_mgr.h
=> reboot and guestos purging fixes

common/event.c
Seems necessary to register the epoll io event handler on the initify fd after the event_inotify_t is added to the event internal list. We remove and read the io handler now each time a watch is added to the corrsponding inotify instance.
=> common/event: register event_inotify_io after notify_add_watch()

daemon/cmld.c, daemon/cmld.h, daemon/guestos_mgr.c, daemon/mount.c, daemon/mount.h
* mnt: two new functions which allow to calculate necessary disk space for a given mount-table of a container or guestos
* cmld: check whether enough disk space is left before container creation
* guestos_mgr: check whether enough disk space is left before downloading guestos image
=> daemon/mnt,cmld,guestos_mgr: Disk space check

daemon/c_seccomp.c
Refactor the BPF filter so that the allowed architecture is determined at compile time and not hard-coded to x86. Only insert the X32_SYSCALL_BIT check when compiling for x86. The new filter can be extended (if required) to support secondary architectures in compatibility mode (x86_64 -> i386, aarch64 -> arm). At the moment syscalls using the compatibility architecture are all blocked and processes are killed.
We do not implement a second architecture at the moment due to the lack of a dependable source of secondary architecture syscall numbers for all architectures.
=> daemon/c_seccomp: Refactor BPF filter for multiarch support

scd/control.c
Do compute- and time-intense crypto operations concurrently in worker children. Thus, the scd remains responsive on requests during hashing of large images for instance. Related protobuf message codes which are now handled in worker children are:
- DAEMON_TO_TOKEN__CODE__CRYPTO_HASH_FILE
- DAEMON_TO_TOKEN__CODE__CRYPTO_HASH_BUF
- DAEMON_TO_TOKEN__CODE__CRYPTO_VERIFY_FILE
- DAEMON_TO_TOKEN__CODE__CRYPTO_VERIFY_BUF
=> scd/control: handle CRYPTO_(HASH|VERIFY)_* msgs in worker children

daemon/download.c, daemon/guestos.c
1. fix uninitialised struct member
2. fix logic bug
3. implement container-relative download urls
=> Guestos Updates

daemon/c_seccomp.c
ARM64 does not provide the mknod syscall (SYS_mknod is not defined) which preventes compilation. Therefore do not handle the syscall on arm64.
=> daemon/c_seccomp: Disable mknod handling for arm64

Jenkinsfile, daemon/c_seccomp/seccomp.c
1. Disable SYS_mknod usage on aarch64
2. Test PRs on both x86 and aarch64 builds
=> SYS_mknod + Jenkinsfile

daemon/c_net.c
To avoid name clashes on container tear down, we have to rename the
physical interfaces which where moved to the container. Otherwise,
situations occur where the interfaces was renamed inside the container
clashes with an interface inside the rootns. This may lead to dangling
network namespace, which keeps the corresponding physical interface
forever.
After container init has died we now rename physical interfaces in
the corresponding cleanup() hook. We fork and join the container netns
by the corresponding path in the file system and use the helper
hotplug_rename_ifi() on all physical network interfaces inside the
container.
=> daemon/c_net: Rename physical interfaces during container cleanup

daemon/audit.c
We missed to truncate the logfile after the buffer with the purged log message was written back to the log file. This caused logfile to grow until memory exhaustion.
This fixes following error trace:
<ERROR> audit.c+154: Detected audit log overflow
<ERROR> audit.c+416: Failed to store audit record: max. log size exceeded
<ERROR> audit.c+656: Failed to store audit log for container 00000000-0000-0000-0000-000000000000 to file
<DEBUG> mem.c+52: Allocating a large memory area of 17232822398 bytes
<DEBUG> mem.c+52: Allocating a large memory area of 34465644670 bytes
<FATAL> mem.c+54: Assertion `p' failed
<FATAL> mem.c+54: Aborting...
Fixes: 526d6ccf99d3 ("daemon/audit: locking of audit log file")
=> daemon/audit: truncate logfile on message purge

daemon/cc_mode/guestos.proto
Allow upstream version for CC_mode build.
=> cc_mode/guestos.proto: Add upstream version

daemon/cc_mode/control.proto
Add 'remove_logs' parameter to the cc_mode
control.proto.
=> daemon/cc_mode/control: enable log removal feature

daemon/c_seccomp/seccomp.c
The riscv32/64 Linux builds does not offer mknod (all done using mknodat), therefore disable use of SYS_mknod on those architectures
=> daemon/c_seccomp/seccomp: Disable SYS_mknod on riscv
